In [1]:
import pandas as pd
import os
from sqlalchemy import create_engine, text

In [2]:
host = "localhost"
user = "root"
password = "LenovoIdeapad"
database = "premior_db"

In [3]:
engine = create_engine(
    f"mysql+pymysql://{user}:{password}@{host}"
)

In [4]:
with engine.connect() as conn:
    conn.execute(text(f"CREATE DATABASE IF NOT EXISTS {database}"))
    conn.commit()

print(f"Database '{database}' created successfully.")

Database 'premior_db' created successfully.

In [5]:
engine = create_engine(
    f"mysql+pymysql://{user}:{password}@{host}/{database}"
)

In [6]:
folder_path = r"D:\Projects\Premior Internship"

In [7]:
csv_files = [file for file in os.listdir(folder_path) if file.endswith(".csv")]

print(csv_files)

['Cleaned_dataset.csv']

In [8]:
for file in csv_files:

    file_path = os.path.join(folder_path, file)

    table_name = os.path.splitext(file)[0].lower()

    print(f"Uploading {table_name}...")

    df = pd.read_csv(file_path)

    df.to_sql(
        name=table_name,
        con=engine,
        if_exists="replace",
        index=False,
        chunksize=1000,
        method="multi"
    )

    print(f"{table_name} uploaded successfully.")

Uploading cleaned_dataset...
cleaned_dataset uploaded successfully.

In [9]:
query = "SHOW TABLES"

tables = pd.read_sql(query, engine)

tables

  Tables_in_premior_db
0      cleaned_dataset

In [11]:
for file in csv_files:

    file_path = os.path.join(folder_path, file)

    df = pd.read_csv(file_path)

    print(f"{file} : {df.shape}")

Cleaned_dataset.csv : (51271, 21)

In [12]:
df = pd.read_csv(file_path)

In [13]:
df.head(5)

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
0,AG-2011-2040,01-01-2011,06-01-2011,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Office Supplies,Storage,"Tenex Lockers, Blue",408.0,2.0,0.0,106.14,35.46,Medium,2011
1,IN-2011-47883,01-01-2011,08-01-2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Office Supplies,Supplies,"Acme Trimmer, High Speed",120.0,3.0,0.1,36.04,9.72,Medium,2011
2,HU-2011-1220,01-01-2011,05-01-2011,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Office Supplies,Storage,"Tenex Box, Single Width",66.0,4.0,0.0,29.64,8.17,High,2011
3,IT-2011-3647632,01-01-2011,05-01-2011,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Office Supplies,Paper,"Enermax Note Cards, Premium",45.0,3.0,0.5,-26.06,4.82,High,2011
4,IN-2011-47883,01-01-2011,08-01-2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furniture,Furnishings,"Eldon Light Bulb, Duo Pack",114.0,5.0,0.1,37.77,4.70,Medium,2011

In [14]:
df.tail(5)

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,category,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year
51266,CA-2014-115427,31-12-2014,04-01-2015,Standard Class,Erica Bern,Corporate,California,United States,US,West,...,Office Supplies,Binders,"Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl",14.0,2.0,0.2,4.52,0.89,Medium,2014
51267,MO-2014-2560,31-12-2014,05-01-2015,Standard Class,Liz Preis,Consumer,Souss-Massa-Draâ,Morocco,Africa,Africa,...,Office Supplies,Binders,"Wilson Jones Hole Reinforcements, Clear",4.0,1.0,0.0,0.42,0.49,Medium,2014
51268,MX-2014-110527,31-12-2014,02-01-2015,Second Class,Charlotte Melton,Consumer,Managua,Nicaragua,LATAM,Central,...,Office Supplies,Labels,"Hon Color Coded Labels, 5000 Label Set",26.0,3.0,0.0,12.36,0.35,Medium,2014
51269,MX-2014-114783,31-12-2014,06-01-2015,Standard Class,Tamara Dahlen,Consumer,Chihuahua,Mexico,LATAM,North,...,Office Supplies,Labels,"Hon Legal Exhibit Labels, Alphabetical",7.0,1.0,0.0,0.56,0.20,Medium,2014
51270,CA-2014-156720,31-12-2014,04-01-2015,Standard Class,Jill Matthias,Consumer,Colorado,United States,US,West,...,Office Supplies,Fasteners,Bagged Rubber Bands,3.0,3.0,0.2,-0.60,0.17,Medium,2014

In [ ]:
df.